### ISSUE TITLE
Does not actually work on Linux

### ISSUE THREAD

**Issue by mrdudz** [jpage8580/GTUltra#9]
After applying the missing patch mentioned in #1 building works, but the resulting binary will not run:
```
$ ./gt2stereo 

MidiInDummy: This class provides no functionality.
```
Don't have time to dig further into this, but the case that MIDI isnt available (ie the dummy driver is used) doesnt seem to work at all.

**Comment by drfiemost** [comment]
That message should only be a warning, on MSYS2 it starts fine.
To enable midi on Linux you have to define __LINUX_ALSA__, but I think there is something else going wrong.

**Comment by mrdudz** [comment]
It just exits immediately :) defining __LINUX_ALSA__ gives linker errors again (some prototypes dont match)

**Comment by drfiemost** [comment]
Works for me, in RtMidi.cpp I've replaced
`#define __WINDOWS_MM__`
with
`#define __LINUX_ALSA__`

And in the makefile I've added the alsa flags
```
CFLAGS+=`sdl-config --cflags` `pkg-config --cflags alsa`
LIBS+=`sdl-config --libs` `pkg-config --libs alsa`
```
It starts and I can connect the midi controller using QJackCtl

**Comment by jpage8580** [comment]
Hopefully linux support is better. I included those changes. ^^
Thank you!

**Comment by fieserWolF** [comment]
Hi there,

linking does not work on my machine: Linux 5.16.0-3-amd64 #1 SMP PREEMPT Debian 5.16.11-1 (2022-02-25) x86_64 GNU/Linux. First, I fixed some issues.

**First issue was:**
```
cc `sdl2-config --cflags` `pkg-config --cflags alsa` -Ibme -Iasm -O3 -fpermissive   -c -o gt2stereo.o gt2stereo.c
cc1: warning: command-line option ‘-fpermissive’ is valid for C++/ObjC++ but not for C
gt2stereo.c:27:10: fatal error: bme\bme.h: Datei oder Verzeichnis nicht gefunden
   27 | #include "bme\bme.h"
      |          ^~~~~~~~~~~
compilation terminated.
make: *** [<eingebaut>: gt2stereo.o] Fehler 1
```
**fix** in "gt2stereo.c", line 27: #include "bme/bme.h"


**Second issue was:**
```
g++ `sdl2-config --cflags` `pkg-config --cflags alsa` -Ibme -Iasm -O3 -fpermissive   -c -o RtMidi.o RtMidi.cpp
RtMidi.cpp:201:14: error: conflicting return type specified for ‘virtual void MidiInAlsa::initialize(const string&)’
  201 |         void initialize(const std::string& clientName);
      |              ^~~~~~~~~~
In file included from RtMidi.cpp:46:
RtMidi.h:551:38: note: overridden function is ‘virtual unsigned int MidiApi::initialize(const string&)’
  551 |                 virtual unsigned int initialize(const std::string& clientName) = 0;
      |                                      ^~~~~~~~~~
RtMidi.cpp:220:14: error: conflicting return type specified for ‘virtual void MidiOutAlsa::initialize(const string&)’
  220 |         void initialize(const std::string& clientName);
      |              ^~~~~~~~~~
In file included from RtMidi.cpp:46:
RtMidi.h:551:38: note: overridden function is ‘virtual unsigned int MidiApi::initialize(const string&)’
  551 |                 virtual unsigned int initialize(const std::string& clientName) = 0;
      |                                      ^~~~~~~~~~
make: *** [<eingebaut>: RtMidi.o] Fehler 1
```
**fix** in "RtMidi.h", line 551:
old:		virtual unsigned int initialize(const std::string& clientName) = 0;
new:	virtual void initialize(const std::string& clientName) = 0;
(see original sourcecode, line 542 at https://www.music.mcgill.ca/~gary/rtmidi/RtMidi_8h_source.html)


**Third issue was:**
```
/usr/bin/ld: RtMidi.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
/usr/bin/ld: /lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
```
**fix** in "makefile", line 8:
old:    LIBS+=`sdl2-config --libs` `pkg-config --libs alsa`
new:    LIBS+=`sdl2-config --libs` `pkg-config --libs alsa` -lpthread


**Fourth issue is:**
```
g++ -o ../linux/gt2stereo goatdata.o gt2stereo.o gsong.o gorder.o gpattern.o ginstr.o gtable.o gplay.o gdisplay.o gfile.o greloc.o ghelp.o gsound.o gconsole.o gsid.o ginfo.o gmidi.o gundo.o gchareditor.o RtMidi.o resid/envelope.o resid/extfilt.o resid/filter.o resid/pot.o resid/sid.o resid/wave.o resid/wave6581__ST.o resid/wave6581_P_T.o resid/wave6581_PS_.o resid/wave6581_PST.o resid/wave8580__ST.o resid/wave8580_P_T.o resid/wave8580_PS_.o resid/wave8580_PST.o resid/voice.o resid-fp/envelopefp.o resid-fp/extfiltfp.o resid-fp/filterfp.o resid-fp/potfp.o resid-fp/sidfp.o resid-fp/wavefp.o resid-fp/voicefp.o asm/asmtab.o asm/chnkpool.o asm/expr.o asm/lexyy.o asm/log.o asm/membuf.o asm/membufio.o asm/namedbuf.o asm/parse.o asm/pc.o asm/vec.o bme/bme_gfx.o bme/bme_snd.o bme/bme_win.o bme/bme_mou.o bme/bme_kbd.o bme/bme_io.o bme/bme_end.o bme/bme.o `sdl2-config --libs` `pkg-config --libs alsa` -lpthread
/usr/bin/ld: gsong.o:(.bss+0x1fd8940): multiple definition of `jdebug'; gt2stereo.o:(.bss+0x23a0): first defined here
/usr/bin/ld: gorder.o:(.bss+0xd660): multiple definition of `jdebug'; gt2stereo.o:(.bss+0x23a0): first defined here
/usr/bin/ld: gpattern.o:(.bss+0xce0): multiple definition of `jdebug'; gt2stereo.o:(.bss+0x23a0): first defined here
/usr/bin/ld: ginstr.o:(.bss+0x20): multiple definition of `jdebug'; gt2stereo.o:(.bss+0x23a0): first defined here
/usr/bin/ld: gtable.o:(.bss+0x220): multiple definition of `jdebug'; gt2stereo.o:(.bss+0x23a0): first defined here
/usr/bin/ld: gplay.o:(.bss+0x4380): multiple definition of `jdebug'; gt2stereo.o:(.bss+0x23a0): first defined here
/usr/bin/ld: gdisplay.o:(.bss+0x4c0): multiple definition of `jdebug'; gt2stereo.o:(.bss+0x23a0): first defined here
/usr/bin/ld: gfile.o:(.bss+0x40000): multiple definition of `jdebug'; gt2stereo.o:(.bss+0x23a0): first defined here
/usr/bin/ld: greloc.o:(.bss+0x1780): multiple definition of `jdebug'; gt2stereo.o:(.bss+0x23a0): first defined here
/usr/bin/ld: ghelp.o:(.bss+0x0): multiple definition of `jdebug'; gt2stereo.o:(.bss+0x23a0): first defined here
/usr/bin/ld: gsound.o:(.bss+0x60): multiple definition of `jdebug'; gt2stereo.o:(.bss+0x23a0): first defined here
/usr/bin/ld: gconsole.o:(.bss+0x120): multiple definition of `jdebug'; gt2stereo.o:(.bss+0x23a0): first defined here
/usr/bin/ld: ginfo.o:(.bss+0x20): multiple definition of `jdebug'; gt2stereo.o:(.bss+0x23a0): first defined here
/usr/bin/ld: gundo.o:(.bss+0x140): multiple definition of `jdebug'; gt2stereo.o:(.bss+0x23a0): first defined here
/usr/bin/ld: gchareditor.o:(.bss+0x1c0): multiple definition of `jdebug'; gt2stereo.o:(.bss+0x23a0): first defined here
collect2: error: ld returned 1 exit status
make: *** [makefile.common:25: ../linux/gt2stereo] Fehler 1

```
As there is no real error given here, I do not know how to proceed. Any ideas? Thanks a lot!

**Comment by jpage8580** [comment]
Hi 
Hopefully the merge I made today fixes these. Can you try the latest version and let me know if you still have these problems?

**Comment by fieserWolF** [comment]
Hi jpageThanks for the effort! Can test tomorrow evening, ain't at home over the weekendWolfVon meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: jpage8580 ***@***.***> Datum: 02.04.22  13:38  (GMT+01:00) An: jpage8580/GTUltra ***@***.***> Cc: fieserWolF ***@***.***>, Comment ***@***.***> Betreff: Re: [jpage8580/GTUltra] Does not actually work on Linux (Issue #9) 
Hi
Hopefully the merge I made today fixes these. Can you try the latest version and let me know if you still have these problems?

**Comment by drfiemost** [comment]
IIRC libpthread is just a stub on latest glibc so it links fine even without on my machine, but for older versions yes, it is required.

**Comment by fieserWolF** [comment]
Compiling + running under Debian bookworm works like a charm now, thanks a lot!
I just had to add "-lpthread" in the makefile, that was all.

**Comment by jpage8580** [comment]
CN you copy/paste the line for the male file
Here / do a pull request?  I’ll add it. Just want to make sure it’s exactly
as it should be

Thanks!

**Comment by jpage8580** [comment]
Added -lpthread to makefile in V1.1.1
Thanks, all.
